name: Validate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  validate:
    env:
      GOLANG_CI_LINT: go run github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
    name: validate
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: lint
        run: |
          ${GOLANG_CI_LINT} run --disable wsl ./...

      - name: test
        run: |
          go test ./...
